/* VANES AI frontend runtime — authoritative UI layer + Tanzanian ACSEE paper structure. */
(function(){
'use strict';
const subjects=[
['Kiswahili','O-Level','Sarufi, fasihi, ufahamu na uandishi'],['English Language','O-Level','Grammar, comprehension, writing and communication'],['Basic Mathematics','O-Level','Numbers, algebra, geometry, statistics and problem solving'],['Basic Applied Mathematics','O-Level','Commercial arithmetic, graphs, statistics and applications'],['History','O-Level','Tanzania, Africa, colonialism, nationalism and world history'],['Geography','O-Level','Map work, climate, population, resources, development and fieldwork'],['Chemistry','O-Level','Atomic structure, bonding, reactions, acids, bases and organic chemistry'],['Physics','O-Level','Measurement, mechanics, heat, waves, electricity and practical physics'],['Biology','O-Level','Cells, nutrition, transport, reproduction, genetics, ecology and health'],['Civics','O-Level','Citizenship, democracy, human rights, government and governance'],['Information and Computer Studies','O-Level','Computer systems, information, networks and digital skills'],['Commerce','O-Level','Trade, business, banking, insurance, transport and marketing'],['Bookkeeping','O-Level','Double entry, journals, ledgers, trial balance and final accounts'],['Agriculture','O-Level','Soils, crops, livestock, farm management and sustainable agriculture'],['Food and Nutrition','O-Level','Nutrition, food preparation, hygiene and meal planning'],['Fine Art','O-Level','Drawing, design, colour, visual communication and art appreciation'],['Music','O-Level','Music theory, notation, performance and appreciation'],['French','O-Level','French grammar, vocabulary, comprehension and communication'],['Arabic','O-Level','Arabic language, grammar, reading and communication'],['Bible Knowledge','O-Level','Biblical studies, interpretation and Christian knowledge'],['Islamic Knowledge','O-Level',"Qur'an, Hadith, Islamic history and values"],['Physical Education','O-Level','Fitness, health, games and sports'],['Economics','O-Level','Economic concepts, markets, production and development'],['Business Studies','O-Level','Entrepreneurship, management, marketing and business planning'],['Computer Applications','O-Level','Word processing, spreadsheets, presentations and data management'],
['Advanced Mathematics','A-Level','Functions, algebra, trigonometry, calculus, vectors, probability and statistics'],['Economics','A-Level','Microeconomics, macroeconomics, national income, trade and development'],['History','A-Level','Advanced historical analysis, Africa, Tanzania and global change'],['Geography','A-Level','Advanced physical and human geography, development and fieldwork'],['Physics','A-Level','Mechanics, electricity, waves, thermal physics and modern physics'],['Chemistry','A-Level','Physical, inorganic and organic chemistry with practical work'],['Biology','A-Level','Advanced genetics, physiology, ecology, evolution and practical biology'],['Historia ya Tanzania','A-Level','Tanzania-focused history, colonial rule, nationalism, independence, union and development'],['Academic Communication','A-Level','Academic reading, writing, study skills, note taking and communication'],['Kiswahili','A-Level','Lugha, fasihi, uchambuzi na mawasiliano ya kitaaluma'],['Computer Science','A-Level','Algorithms, programming, databases, networks and cybersecurity'],['Accountancy','A-Level','Financial accounting, partnerships, companies, analysis and budgeting'],['Commerce','A-Level','Business systems, trade, finance, marketing and management'],['Business Studies','A-Level','Management, marketing, finance, human resources and strategy'],['Computer Applications','A-Level','Advanced productivity, data analysis and information management']
].map(x=>({name:x[0],level:x[1],lesson:x[2],description:x[2]+'. VANES can explain, practise, analyse and revise this area.'}));

// ACSEE paper structure used by VANES study cards. Science practical subjects have Paper 1,
// Paper 2 and Paper 3. Tanzania History and Academic Communication are single-paper subjects.
const paperMap={
 'Physics':3,'Chemistry':3,'Biology':3,
 'Advanced Mathematics':2,'Economics':2,'History':2,'Geography':2,'Kiswahili':2,
 'English Language':2,'Historia ya Tanzania':1,'Academic Communication':1,
 'Computer Science':2,'Accountancy':2,'Commerce':2,'Business Studies':2,'Computer Applications':2
};
const papers=n=>Array.from({length:paperMap[n]||2},(_,i)=>`Paper ${i+1}`);
const topics={
'Kiswahili':['Sarufi','Fasihi simulizi','Fasihi andishi','Ufahamu','Uandishi','Mawasiliano','Msamiati'],
'English Language':['Grammar','Comprehension','Vocabulary','Writing','Oral communication','Summary writing','Functional writing'],
'Basic Mathematics':['Numbers','Algebra','Equations','Geometry','Mensuration','Trigonometry','Statistics','Probability','Sets','Sequences','Coordinate geometry','Financial mathematics'],
'Basic Applied Mathematics':['Commercial arithmetic','Ratio and proportion','Percentages','Rates','Graphs','Statistics','Measurement','Financial mathematics','Linear programming'],
'Advanced Mathematics':['Algebra','Functions','Polynomials','Sequences and series','Trigonometry','Vectors','Matrices','Differentiation','Integration','Differential equations','Probability','Statistics'],
'History':['Pre-colonial African societies','Slave trade','Colonialism','Nationalism','African independence','Tanzania and Tanganyika','World Wars','Cold War','Post-independence Africa'],
'Geography':['Map reading','Weather and climate','Geomorphology','Soils','Vegetation','Water resources','Population','Settlement','Agriculture','Industry','Transport','Tourism','Environment','Fieldwork','Development'],
'Chemistry':['Matter','Atomic structure','Periodic table','Chemical bonding','Formulae and equations','Mole concept','Chemical reactions','Acids, bases and salts','Organic chemistry','Metals','Rates of reaction','Energy changes','Electrochemistry','Qualitative analysis'],
'Physics':['Measurement','Mechanics','Motion','Forces','Work, energy and power','Pressure','Heat','Waves','Light','Sound','Electricity','Magnetism','Electromagnetism','Atomic physics','Practical physics'],
'Biology':['Cells','Nutrition','Transport','Respiration','Excretion','Coordination','Reproduction','Genetics','Evolution','Ecology','Microorganisms','Health and diseases','Classification','Practical biology'],
'Civics':['Citizenship','Democracy','Human rights','Government','Constitution','Rule of law','Good governance','National identity','Gender','Culture','Globalisation','Environment'],
'Economics':['Basic economic concepts','Demand and supply','Elasticity','Production','Market structures','National income','Money and banking','Inflation','Unemployment','Public finance','International trade','Economic development'],
'Commerce':['Trade','Business units','Entrepreneurship','Banking','Insurance','Warehousing','Transport','Communication','Marketing','Consumer protection'],
'Bookkeeping':['Accounting concepts','Source documents','Double entry','Journals','Ledgers','Cash book','Trial balance','Bank reconciliation','Depreciation','Errors','Final accounts'],
'Agriculture':['Soils','Crop production','Crop pests and diseases','Livestock production','Animal nutrition','Farm tools','Farm management','Agricultural economics','Irrigation','Sustainable agriculture'],
'Computer Science':['Algorithms','Programming','Data structures','Databases','Computer architecture','Operating systems','Networks','Cybersecurity','Software engineering','Web technology'],
'Accountancy':['Accounting principles','Books of original entry','Ledgers','Trial balance','Final accounts','Partnership','Company accounts','Cost accounting','Financial analysis','Budgeting','Auditing'],
'Business Studies':['Entrepreneurship','Business environment','Management','Marketing','Finance','Human resources','Production','Trade','Business law','Business planning'],
'Computer Applications':['Office applications','Data management','Presentations','Spreadsheets','Word processing','Internet','Digital communication','Information management'],
'Historia ya Tanzania':['Pre-colonial societies','German colonial rule','British colonial rule','Nationalism and independence','Tanganyika independence','Union of Tanganyika and Zanzibar','Tanzania after independence','Political and economic development'],
'Academic Communication':['Academic reading','Academic writing','Study skills','Note taking','Summarising','Referencing','Presentation skills','Academic vocabulary']};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=s=>s.level+'::'+s.name;
const get=k=>subjects.find(s=>key(s)===k)||subjects[0];
function toast(t){const e=document.querySelector('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__vanesToast);window.__vanesToast=setTimeout(()=>e.classList.remove('show'),2400)}
window.showToast=window.showToast||toast;
function view(id){document.querySelectorAll('.view').forEach(e=>e.classList.toggle('active',e.id===id));document.querySelectorAll('.nav-link').forEach(e=>e.classList.toggle('active',e.dataset.view===id));document.querySelector('.sidebar')?.classList.remove('open');window.scrollTo(0,0);location.hash=id}
window.VANES_SWITCH_VIEW=view;
function paperMarkup(name,level){if(level!=='A-Level')return '';return `<div class="vanes-paper-row" aria-label="Examination papers">${papers(name).map(p=>`<span class="vanes-paper-badge">${p}</span>`).join('')}</div>`}
function renderSubjects(filter='all'){const g=document.querySelector('#subjectGrid');if(!g)return;const list=filter==='all'?subjects:subjects.filter(s=>s.level===filter);g.innerHTML=list.map(s=>{const ts=(topics[s.name]||[s.lesson]).slice(0,4);return `<article class="panel subject-card" tabindex="0" data-subject="${esc(key(s))}"><div class="subject-top"><span class="subject-icon">✦</span><span class="pill">${esc(s.level)}</span></div><h2>${esc(s.name)}</h2><p>${esc(s.lesson)}</p><div class="topic-preview">${ts.map(t=>`<span>${esc(t)}</span>`).join('')}</div>${paperMarkup(s.name,s.level)}<div class="subject-progress"><div><span style="width:0%"></span></div>0%</div></article>`}).join('');g.querySelectorAll('[data-subject]').forEach(e=>{const open=()=>openSubject(e.dataset.subject);e.addEventListener('click',open);e.addEventListener('keydown',x=>{if(x.key==='Enter'||x.key===' ')open()})})}
function renderDashboard(){const b=document.querySelector('#dashboardSubjects');if(!b)return;const list=[...subjects].slice(0,10),items=[...list,...list];b.innerHTML='<div class="dashboard-slide-track">'+items.map((s,i)=>`<article class="topic" tabindex="0" data-subject="${esc(key(s))}" data-slide-copy="${i>=list.length?'true':'false'}"><span class="topic-icon">✦</span><div><strong>${esc(s.name)}</strong><p>${esc(s.level)} · ${esc(s.lesson)}</p>${paperMarkup(s.name,s.level)}</div><span class="topic-arrow">→</span></article>`).join('')+'</div>';b.querySelectorAll('[data-subject]').forEach(e=>{const open=()=>openSubject(e.dataset.subject);e.addEventListener('click',open);e.addEventListener('keydown',x=>{if(x.key==='Enter'||x.key===' ')open()})})}
function openSubject(k){const s=get(k);window.VANES_SELECTED_SUBJECT={name:s.name,level:s.level,lesson:s.lesson};document.body.dataset.vanesActiveSubject=s.name;document.querySelector('#workspaceLabel').textContent=`${s.name.toUpperCase()} · ${s.level}`;document.querySelector('#workspaceTitle').textContent=s.name;document.querySelector('#workspaceDescription').textContent=s.description;document.querySelector('#sessionTitle').textContent=`Start with ${s.lesson}`;const map=document.querySelector('#topicMap');if(map){if(s.level==='A-Level'){map.innerHTML=papers(s.name).map(p=>`<div class="vanes-paper-section"><h3>${p}</h3><div class="paper-topics">${(topics[s.name]||[s.lesson]).map(t=>`<button class="topic-chip" type="button" data-topic="${esc(t)}">${esc(t)}</button>`).join('')}</div></div>`).join('')}else map.innerHTML=(topics[s.name]||[s.lesson]).map(t=>`<button class="topic-chip" type="button" data-topic="${esc(t)}">${esc(t)}</button>`).join('');}
document.querySelector('#sessionSteps').innerHTML=['Select the paper you are preparing for.','Study the topics and practise exam-style questions.','Review your mistakes and strengthen weak areas.','Finish with a timed self-test.'].map(x=>`<li>${x}</li>`).join('');view('workspace')}
function profile(){const n=localStorage.getItem('vanes-user-name');const name=n||'Student';const p=document.querySelector('#profileName'),a=document.querySelector('#profileAvatar'),w=document.querySelector('#welcomeTitle');if(p)p.textContent=name;if(a)a.textContent=name.charAt(0).toUpperCase();if(w)w.textContent=n?`Make today count, ${name}.`:'Make today count.';const m=document.querySelector('#nameModal');if(n){m?.classList.remove('show');m?.setAttribute('aria-hidden','true')}else{m?.classList.add('show');m?.setAttribute('aria-hidden','false')}}
function injectPaperStyles(){if(document.getElementById('vanes-paper-styles'))return;const s=document.createElement('style');s.id='vanes-paper-styles';s.textContent='.vanes-paper-row{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.vanes-paper-badge{display:inline-flex;align-items:center;padding:5px 9px;border-radius:999px;border:1px solid currentColor;font-size:11px;font-weight:800}.vanes-paper-section{margin:10px 0 14px}.vanes-paper-section h3{margin:0 0 7px;font-size:13px}.paper-topics{display:flex;flex-wrap:wrap;gap:7px}';document.head.appendChild(s)}
const ACTIVITY_LOG='vanes-study-activity-v1';
function readActivity(){try{const x=JSON.parse(localStorage.getItem(ACTIVITY_LOG)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
/* Learners are in UTC+3, so UTC day strings put evening study on the wrong day
   and make every streak one day short. All day keys are local. */
function localDay(ts){const d=new Date(Number(ts)||Date.now());return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function recordStudyActivity(data={}){const now=Date.now(),day=localDay(now),log=readActivity(),subject=data.subject||'',level=data.level||'',seconds=Math.max(0,Number(data.seconds||0));let item=log.find(x=>x.day===day&&x.subject===subject&&x.level===level);if(!item){item={day,at:now,subject,level,seconds:0};log.push(item)}item.at=now;item.seconds=Number(item.seconds||0)+seconds;localStorage.setItem(ACTIVITY_LOG,JSON.stringify(log.slice(-365)));updateDashboardStats()}
function updateDashboardStats(){const minutes=document.querySelector('#minutesStat'),progress=document.querySelector('#progressStat'),bar=document.querySelector('#progressBar');if(!minutes&&!progress)return;const now=Date.now(),todayDate=new Date(),dayOffset=(todayDate.getDay()+6)%7,weekStartDate=new Date(todayDate.getFullYear(),todayDate.getMonth(),todayDate.getDate()-dayOffset),weekStart=weekStartDate.getTime(),log=readActivity(),active=(()=>{try{return JSON.parse(localStorage.getItem('vanes-active-session-v2')||'null')}catch{return null}})();let seconds=log.filter(x=>Number(x.at)>=weekStart).reduce((n,x)=>n+Number(x.seconds||0),0);if(active?.startedAt){const activeDay=localDay(active.startedAt),today=localDay(now);if(activeDay===today)seconds+=Math.max(0,Math.floor((now-Number(active.startedAt))/1000))}const weekDays=new Set(log.filter(x=>Number(x.at)>=weekStart).map(x=>x.day));if(active?.startedAt)weekDays.add(localDay(now));const recentDays=new Set(log.map(x=>x.day));if(active?.startedAt)recentDays.add(localDay(now));let streak=0,cursor=new Date();cursor.setHours(0,0,0,0);for(;;){const expected=localDay(cursor.getTime());if(!recentDays.has(expected))break;streak++;cursor.setDate(cursor.getDate()-1)}const profile=(()=>{try{return JSON.parse(localStorage.getItem('vanes-learner-profile-v2')||localStorage.getItem('vanes-learner-profile-v1')||'null')}catch{return null}})();const level=profile?.level||'O-Level';const relevant=subjects.filter(x=>x.level===level),total=relevant.length||subjects.length;const studiedSet=new Set(log.filter(x=>x.level===level&&Number(x.seconds||0)>0).map(x=>x.subject).filter(Boolean));if(active?.subject&&active?.level===level)studiedSet.add(active.subject);const studied=studiedSet.size;const pct=Math.min(100,Math.round(studied/total*100));if(minutes){const m=Math.floor(seconds/60);minutes.textContent=m<60?m+' min':Math.floor(m/60)+'h '+(m%60)+'m';const note=minutes.parentElement?.querySelector('small');if(note)note.textContent=weekDays.size?weekDays.size+' study day'+(weekDays.size===1?'':'s')+' this week':'Start a session to build your week'}const streakEl=minutes?.closest('.stats-grid')?.querySelector('article:nth-child(2) strong');if(streakEl)streakEl.textContent=streak+' day'+(streak===1?'':'s');const streakNote=streakEl?.parentElement?.querySelector('small');if(streakNote)streakNote.textContent=streak?'Keep it going!':'Start studying today';if(progress)progress.textContent=pct+'%';if(bar)bar.style.width=pct+'%'}
function init(){injectPaperStyles();document.querySelectorAll('[data-view]').forEach(e=>e.addEventListener('click',x=>{x.preventDefault();view(e.dataset.view)}));document.querySelectorAll('[data-view-target]').forEach(e=>e.addEventListener('click',()=>view(e.dataset.viewTarget)));/* #mobileMenu is owned by vanes-mobile.js; a second toggle here closed the menu again. */document.querySelectorAll('.filter-button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSubjects(b.dataset.filter)}));/* Learner profile creation/editing is owned by vanes-profile.js. Keeping one owner
   prevents duplicate submit handlers and conflicting localStorage writes. */updateDashboardStats();window.VANES_RECORD_STUDY_ACTIVITY=recordStudyActivity;/* The planner form is submitted through vanes-send-fix.js (capture-phase handler). */document.querySelector('#completeSession')?.addEventListener('click',()=>toast('Session marked complete ✓'));renderSubjects();renderDashboard();profile();const hash=location.hash.slice(1);if(isView(hash))view(hash);
/* Back/forward only changes the hash; without this the view never follows. */
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(isView(id))view(id)})}
function isView(id){return Boolean(id)&&Boolean(document.getElementById(id)?.classList.contains('view'))}
window.addEventListener('storage',e=>{if([ACTIVITY_LOG,'vanes-study-shelf-v2','vanes-active-session-v2','vanes-learner-profile-v2'].includes(e.key))updateDashboardStats()});setInterval(updateDashboardStats,1000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
