const OWNER_EMAIL = "obtechnologies625@gmail.com";
// Private owner transaction details. Configure these as Cloudflare Worker secrets/env vars,
// not in frontend code. The values below are intentionally not rendered or returned to clients.
const OWNER_AIRTEL_NUMBER = "";
const OWNER_AIRTEL_NETWORK = "Airtel";
const allowed = new Set(["donation","family","field","feedback"]);
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"POST,OPTIONS"}})}
function clean(v,max=500){return String(v??"").trim().slice(0,max)}
function validEmail(v){return !v||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function textFor(type,p){if(type==='donation')return `VANES DONATION REQUEST\nAmount: ${clean(p.amount,30)} ${clean(p.currency,10)}\nMethod: ${clean(p.method,30)}\nName: ${clean(p.name,100)}\nPhone: ${clean(p.phone,40)}\nEmail: ${clean(p.email,150)}`;if(type==='family')return `VANES FAMILY MEMBERSHIP REQUEST\nName: ${clean(p.name,100)}\nPhone: ${clean(p.phone,40)}\nEmail: ${clean(p.email,150)}`;if(type==='field')return `OB TECH-LABS FIELD INTEREST\nName: ${clean(p.name,100)}\nPhone: ${clean(p.phone,40)}\nEmail: ${clean(p.email,150)}`;return `VANES FEEDBACK\nComment: ${clean(p.comment,3000)}\nEmail: ${clean(p.email,150)}`}
async function email(env,subject,text){
  if(!env.GOOGLE_APPS_SCRIPT_URL)return false;
  try{
    const r=await fetch(env.GOOGLE_APPS_SCRIPT_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({to:OWNER_EMAIL,subject,text,source:"VANES AI"})});
    return r.ok;
  }catch{return false}
}
async function sms(env,text){if(!env.TWILIO_ACCOUNT_SID||!env.TWILIO_AUTH_TOKEN||!env.TWILIO_FROM_NUMBER||!env.OWNER_PHONE_NUMBER)return false;const body=new URLSearchParams({To:env.OWNER_PHONE_NUMBER,From:env.TWILIO_FROM_NUMBER,Body:text.slice(0,1500)});const auth=btoa(`${env.TWILIO_ACCOUNT_SID}:${env.TWILIO_AUTH_TOKEN}`);const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${env.TWILIO_ACCOUNT_SID}/Messages.json`,{method:"POST",headers:{Authorization:`Basic ${auth}`,"Content-Type":"application/x-www-form-urlencoded"},body});return r.ok}
export async function handleContact(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"POST,OPTIONS"}});if(request.method!=='POST')return json({error:"Method not allowed"},405);let b;try{b=await request.json()}catch{return json({error:"Invalid request."},400)}const type=clean(b?.type,30),p=b?.payload||{};if(!allowed.has(type))return json({error:"Unsupported request."},400);if(!clean(p.name,100)&&type!=='feedback')return json({error:"Name is required."},400);if(!clean(p.phone,40)&&type!=='feedback')return json({error:"Phone number is required."},400);if(type!=='feedback'&&!validEmail(clean(p.email,150)))return json({error:"Please enter a valid email."},400);if(type==='feedback'&&!clean(p.comment,3000))return json({error:"Comment is required."},400);const text=textFor(type,p);const subject={donation:"VANES donation request",family:"VANES family membership request",field:"OB Tech-Labs field interest",feedback:"VANES app feedback"}[type];const ownerTransactionText=type==='donation'&&env.OWNER_AIRTEL_NUMBER?`${text}\n\nPRIVATE OWNER PAYMENT ROUTING: ${OWNER_AIRTEL_NETWORK} ${env.OWNER_AIRTEL_NUMBER}`:text;const [sentEmail,sentSms]=await Promise.all([email(env,subject,ownerTransactionText),sms(env,ownerTransactionText)]);if(!sentEmail&&!sentSms)return json({error:"The request was prepared, but Google Apps Script owner delivery is not configured yet. Add GOOGLE_APPS_SCRIPT_URL to the Cloudflare Worker secrets."},503);if(type==='donation')return json({ok:true,message:sentEmail?"Donation request received. Payment verification is not reported as successful until a supported payment gateway confirms it.":"Donation request received for review."});return json({ok:true,message:sentEmail?"Sent to OB Technologies. Thank you.":"Request sent through the configured notification channel."})}
